import '../../app/constants/app_constants.dart';
import '../models/admin_overview.dart';
import '../models/app_notification.dart';
import '../models/app_user.dart';
import '../models/booking.dart';
import '../models/chat_message.dart';
import '../models/marketplace_catalog.dart';
import '../models/shootr_package.dart';

class BootstrapBundle {
  const BootstrapBundle({
    required this.packages,
    required this.shootrs,
    required this.clients,
    required this.bookings,
    required this.notifications,
    required this.chatThreads,
    required this.adminOverview,
  });

  final List<ShootrPackage> packages;
  final List<AppUser> shootrs;
  final List<AppUser> clients;
  final List<Booking> bookings;
  final List<AppNotification> notifications;
  final Map<String, List<ChatMessage>> chatThreads;
  final AdminOverview adminOverview;
}

class MockMarketplaceService {
  const MockMarketplaceService();

  BootstrapBundle bootstrap() {
    final packages = <ShootrPackage>[
      const ShootrPackage(
        type: ShootrPackageType.basic,
        title: 'Basic',
        description: '1 reel, standard edit.',
        price: 1999,
        inclusions: <String>['1 reel', 'Standard edit', 'Fast delivery'],
      ),
      const ShootrPackage(
        type: ShootrPackageType.pro,
        title: 'Pro',
        description: '2 reels, colour graded, trending audio.',
        price: 3499,
        inclusions: <String>['2 reels', 'Colour grade', 'Trending audio'],
      ),
      const ShootrPackage(
        type: ShootrPackageType.luxe,
        title: 'Luxe',
        description: '3 reels, cinematic grade, custom music.',
        price: 5999,
        inclusions: <String>['3 reels', 'Cinematic grade', 'Custom music'],
      ),
      const ShootrPackage(
        type: ShootrPackageType.drone,
        title: 'Drone Add-on',
        description: 'Aerial shots and cinematic openers.',
        price: 2000,
        isAddon: true,
        inclusions: <String>['Aerial shots', 'Reveal opener', 'Venue sweep'],
        requiresDrone: true,
      ),
    ];

    final shootrs = <AppUser>[
      AppUser(
        id: 'shootr_1',
        role: UserRole.shootr,
        name: 'Rhea Nair',
        phone: '+91 9876543210',
        city: 'Mumbai',
        state: 'Maharashtra',
        photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
        activeSince: DateTime(2023, 6, 18),
        rating: 4.9,
        reviewCount: 182,
        bio: 'Restaurant and lifestyle reel specialist with same-day edits.',
        hourlyRate: 1999,
        distanceKm: 1.4,
        verified: true,
        backgroundVerified: true,
        availableNow: true,
        online: true,
        portfolio: const <String>[
          'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4',
          'https://images.unsplash.com/photo-1528605248644-14dd04022da1',
          'https://images.unsplash.com/photo-1527529482837-4698179dc6ce',
        ],
        reviews: <Review>[
          Review(
            id: 'rv1',
            authorName: 'Anaya',
            authorPhoto: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
            rating: 5,
            comment: 'Fast, clear direction, and the reel converted brilliantly.',
            createdAt: DateTime.now().subtract(const Duration(days: 1)),
          ),
        ],
        badges: const <String>['Top Rated', '100 Shoots', '5-Star'],
        deviceModel: 'iPhone 15 Pro',
        deviceType: DeviceType.iphone,
        deviceTier: DeviceTier.premium,
        deviceCameraSpec: 'ProRes camera',
        availability: const <String>['Weekdays', 'Weekends'],
        todayAvailability: '10:00 AM - 08:00 PM',
        nextAvailableSlot: 'Today 03:30 PM',
        payoutDetails: 'UPI: rhea@upi',
      upiId: 'rhea@upi',
      accountStatus: AccountStatus.active,
      totalShoots: 214,
        reelsDelivered: 482,
        repeatClients: 77,
        completionRate: 98.4,
        responseRate: 96.2,
        onTimeRate: 97.5,
        avgResponseMinutes: 2,
        walletBalance: 18340,
        creditsBalance: 220,
        totalEarned: 468000,
        referralCode: 'RHEA1000',
        specialisationIds: const <String>['restaurant', 'food_blog', 'fashion'],
        latitude: 19.0461,
        longitude: 72.8202,
        operatingRadiusKm: 10,
        hasDrone: true,
        level: levelFromShoots(214),
        identityStatus: VerificationStatus.verified,
        deviceVerificationStatus: VerificationStatus.verified,
      ),
      AppUser(
        id: 'shootr_2',
        role: UserRole.shootr,
        name: 'Kabir Sheikh',
        phone: '+91 9988776655',
        city: 'Mumbai',
        state: 'Maharashtra',
        photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e',
        activeSince: DateTime(2024, 2, 1),
        rating: 4.8,
        reviewCount: 96,
        bio: 'Cinematic brand launch reels and nightlife edits.',
        hourlyRate: 3499,
        distanceKm: 3.1,
        verified: true,
        backgroundVerified: true,
        availableNow: true,
        online: true,
        portfolio: const <String>[
          'https://images.unsplash.com/photo-1511578314322-379afb476865',
          'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee',
        ],
        badges: const <String>['Top Rated'],
        deviceModel: 'iPhone 14 Pro Max',
        deviceType: DeviceType.iphone,
        deviceTier: DeviceTier.premium,
        deviceCameraSpec: '48MP main camera',
        availability: const <String>['Weekends'],
        todayAvailability: '12:00 PM - 10:00 PM',
        nextAvailableSlot: 'Today 06:00 PM',
        payoutDetails: 'UPI: kabir@upi',
      upiId: 'kabir@upi',
      accountStatus: AccountStatus.active,
      totalShoots: 121,
        reelsDelivered: 268,
        repeatClients: 39,
        completionRate: 97.1,
        responseRate: 91.4,
        onTimeRate: 94.8,
        avgResponseMinutes: 4,
        walletBalance: 12880,
        creditsBalance: 160,
        totalEarned: 319000,
        referralCode: 'KABIR1000',
        specialisationIds: const <String>['brand_launch', 'corporate', 'gaming'],
        latitude: 19.0312,
        longitude: 72.8356,
        operatingRadiusKm: 20,
        level: levelFromShoots(121),
        identityStatus: VerificationStatus.verified,
        deviceVerificationStatus: VerificationStatus.verified,
      ),
      AppUser(
        id: 'shootr_3',
        role: UserRole.shootr,
        name: 'Sara Malik',
        phone: '+971 50 234 7788',
        city: 'Dubai',
        photoUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df',
        activeSince: DateTime(2022, 11, 3),
        rating: 4.95,
        reviewCount: 241,
        bio: 'Luxury hospitality and wedding reels for GCC.',
        hourlyRate: 349,
        distanceKm: 2.5,
        verified: true,
        backgroundVerified: true,
        portfolio: const <String>[
          'https://images.unsplash.com/photo-1519225421980-715cb0215aed',
          'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f',
        ],
        badges: const <String>['Top Rated', 'International'],
        deviceModel: 'iPhone 16 Pro',
        deviceType: DeviceType.iphone,
        deviceTier: DeviceTier.premium,
        deviceCameraSpec: 'Pro camera system',
        availability: const <String>['Weekdays'],
        payoutDetails: 'Bank: ENBD xxxx0231',
        accountStatus: AccountStatus.active,
        totalShoots: 311,
        reelsDelivered: 689,
        repeatClients: 144,
        completionRate: 99.2,
        avgResponseMinutes: 3,
        walletBalance: 5410,
        referralCode: 'SARA1000',
      ),
    ];

    final clients = <AppUser>[
      AppUser(
        id: 'client_1',
        role: UserRole.client,
        name: 'Aarav Mehta',
        phone: '+91 9011122233',
        city: 'Mumbai',
        state: 'Maharashtra',
        address: 'Bandra West, Mumbai',
        accountStatus: AccountStatus.active,
        photoUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde',
        activeSince: DateTime(2025, 2, 6),
        rating: 4.7,
        reviewCount: 8,
        walletBalance: 1500,
        creditsBalance: 340,
        totalSpent: 24870,
        referralCode: 'AARAV500',
        savedShootrIds: const <String>['shootr_1'],
        specialisationIds: const <String>['brand_launch', 'restaurant'],
        latitude: 19.0596,
        longitude: 72.8295,
        deliveredReels: <DeliveredReel>[
          DeliveredReel(
            id: 'reel_1',
            title: 'Phoenix Product Reel',
            thumbnailUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865',
            videoUrl: 'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4',
            bookingId: 'BK-2026-0102',
            categoryId: 'product',
            shootrId: 'shootr_2',
            shootrName: 'Kabir Sheikh',
            deliveredAt: DateTime(2026, 3, 12),
          ),
        ],
        walletTransactions: <WalletTransaction>[
          WalletTransaction(
            id: 'credit_1',
            title: 'Shootr Credits earned',
            subtitle: 'Brand Launch booking',
            amount: 180,
            createdAt: DateTime.now().subtract(const Duration(days: 4)),
            isCredit: true,
          ),
        ],
      ),
    ];

    final bookings = <Booking>[
      Booking(
        id: 'BK-2026-0142',
        clientId: 'client_1',
        clientName: 'Aarav Mehta',
        shootrId: 'shootr_1',
        shootrName: 'Rhea Nair',
        packageType: ShootrPackageType.pro,
        scheduledAt: DateTime.now().add(const Duration(hours: 4)),
        durationHours: 2,
        location: const AppLocation(
          address: 'Bandra Fort, Bandra West',
          city: 'Mumbai',
          state: 'Maharashtra',
          latitude: 19.0421,
          longitude: 72.8188,
          landmark: 'Near sea face entrance',
          instructions: 'Call when reaching the parking gate.',
        ),
        categoryId: 'brand_launch',
        eventType: 'Brand Launch',
        stylePreference: 'Cinematic',
        mood: 'Professional',
        musicPreference: 'Energetic',
        reelsNeeded: 2,
        aspectRatio: '9:16',
        referenceLink: 'https://instagram.com/reel/reference',
        baseAmount: 3499,
        platformFee: 175,
        taxAmount: 661,
        status: BookingStatus.confirmed,
        createdAt: DateTime.now().subtract(const Duration(days: 1)),
        qrPayload: 'BK-2026-0142',
        notes: 'Need a launch reel plus founder talking-head cut.',
        promoCode: 'LAUNCH10',
        creditsUsed: 120,
        etaMinutes: 8,
      ),
      Booking(
        id: 'BK-2026-0102',
        clientId: 'client_1',
        clientName: 'Aarav Mehta',
        shootrId: 'shootr_2',
        shootrName: 'Kabir Sheikh',
        packageType: ShootrPackageType.basic,
        scheduledAt: DateTime.now().subtract(const Duration(days: 2)),
        durationHours: 1,
        location: const AppLocation(
          address: 'Phoenix Palladium, Lower Parel',
          city: 'Mumbai',
          state: 'Maharashtra',
          latitude: 18.994,
          longitude: 72.8256,
        ),
        categoryId: 'product',
        eventType: 'Product Shoot',
        stylePreference: 'Minimal',
        mood: 'Professional',
        musicPreference: 'Trending',
        reelsNeeded: 1,
        aspectRatio: '9:16',
        baseAmount: 1999,
        platformFee: 100,
        taxAmount: 378,
        status: BookingStatus.completed,
        createdAt: DateTime.now().subtract(const Duration(days: 5)),
        qrPayload: 'BK-2026-0102',
        etaMinutes: 0,
      ),
      Booking(
        id: 'BK-2026-0201',
        clientId: 'client_1',
        clientName: 'Aarav Mehta',
        shootrId: 'shootr_1',
        shootrName: 'Rhea Nair',
        packageType: ShootrPackageType.luxe,
        scheduledAt: DateTime.now(),
        durationHours: 3,
        location: const AppLocation(
          address: 'Soho House, Juhu',
          city: 'Mumbai',
          state: 'Maharashtra',
          latitude: 19.1074,
          longitude: 72.8263,
        ),
        categoryId: 'restaurant',
        eventType: 'Restaurant',
        stylePreference: 'Aesthetic',
        mood: 'Fun',
        musicPreference: 'Calm',
        reelsNeeded: 3,
        aspectRatio: '9:16',
        baseAmount: 5999,
        platformFee: 300,
        taxAmount: 1134,
        status: BookingStatus.active,
        createdAt: DateTime.now().subtract(const Duration(hours: 3)),
        qrPayload: 'BK-2026-0201',
        etaMinutes: 3,
      ),
    ];

    return BootstrapBundle(
      packages: packages,
      shootrs: shootrs,
      clients: clients,
      bookings: bookings,
      notifications: <AppNotification>[
        AppNotification(
          id: 'ntf_1',
          title: 'Booking confirmed',
          body: 'Rhea accepted your 7:00 PM brand launch booking.',
          createdAt: DateTime.now().subtract(const Duration(minutes: 12)),
          targetRole: UserRole.client,
        ),
        AppNotification(
          id: 'ntf_2',
          title: 'New booking request',
          body: 'Aarav wants to book you at Bandra Fort today.',
          createdAt: DateTime.now().subtract(const Duration(minutes: 5)),
          targetRole: UserRole.shootr,
        ),
        AppNotification(
          id: 'ntf_3',
          title: '3 pending approvals',
          body: 'New Shootr applications are waiting for review.',
          createdAt: DateTime.now().subtract(const Duration(hours: 1)),
          targetRole: UserRole.admin,
        ),
      ],
      chatThreads: <String, List<ChatMessage>>{
        'BK-2026-0142': <ChatMessage>[
          ChatMessage(
            id: 'msg_1',
            bookingId: 'BK-2026-0142',
            senderId: 'shootr_1',
            senderName: 'Rhea Nair',
            body: 'On my way',
            sentAt: DateTime.now().subtract(const Duration(minutes: 18)),
            type: ChatMessageType.quickReply,
            isRead: true,
          ),
          ChatMessage(
            id: 'msg_2',
            bookingId: 'BK-2026-0142',
            senderId: 'client_1',
            senderName: 'Aarav Mehta',
            body: 'Perfect, we will be ready near the sea face.',
            sentAt: DateTime.now().subtract(const Duration(minutes: 16)),
            isRead: true,
          ),
        ],
      },
      adminOverview: const AdminOverview(
        bookingsToday: 148,
        bookingsThisWeek: 932,
        bookingsThisMonth: 3870,
        revenueToday: 486000,
        revenueWeek: 3290000,
        revenueMonth: 13700000,
        activeShootrsOnline: 216,
        newClientSignups: 104,
        newShootrSignups: 29,
        pendingApprovals: 12,
        cityMetrics: <CityMetric>[
          CityMetric(city: 'Mumbai', bookings: 412, revenue: 1480000, activeShootrs: 87),
          CityMetric(city: 'Delhi', bookings: 263, revenue: 910000, activeShootrs: 54),
          CityMetric(city: 'Dubai', bookings: 188, revenue: 1250000, activeShootrs: 41),
          CityMetric(city: 'New York', bookings: 69, revenue: 820000, activeShootrs: 18),
        ],
        revenueTrend: <RevenuePoint>[
          RevenuePoint(dayLabel: 'Mon', value: 3.2),
          RevenuePoint(dayLabel: 'Tue', value: 3.8),
          RevenuePoint(dayLabel: 'Wed', value: 4.1),
          RevenuePoint(dayLabel: 'Thu', value: 4.7),
          RevenuePoint(dayLabel: 'Fri', value: 5.6),
          RevenuePoint(dayLabel: 'Sat', value: 6.3),
          RevenuePoint(dayLabel: 'Sun', value: 4.9),
        ],
      ),
    );
  }

  AppUser createClientProfile({
    required String name,
    required String phone,
    required String city,
    required String photoUrl,
  }) {
    return AppUser(
      id: 'client_1',
      role: UserRole.client,
      name: name,
      phone: phone,
      city: city,
      photoUrl: photoUrl,
      activeSince: DateTime.now(),
      accountStatus: AccountStatus.active,
      walletBalance: 500,
      creditsBalance: 50,
      referralCode: 'NEW500',
    );
  }

  AppUser createShootrProfile({
    required String name,
    required String phone,
    required String city,
    required String stateName,
    required String photoUrl,
    required String deviceModel,
    required DeviceType deviceType,
    required DeviceTier deviceTier,
    required String deviceCameraSpec,
    required String bio,
    required List<String> portfolio,
    required List<String> availability,
    required String todayAvailability,
    required AppCountry country,
    required String address,
    required String pinCode,
    required UserGender gender,
    required DateTime dateOfBirth,
    required String payoutDetails,
    required String upiId,
    required String bankName,
    required String ifscCode,
    required double hourlyRate,
    required List<String> specialisationIds,
    required double latitude,
    required double longitude,
    required int operatingRadiusKm,
    required bool onDemandMode,
    required bool hasDrone,
    required VerificationStatus identityStatus,
    required VerificationStatus deviceVerificationStatus,
  }) {
    return AppUser(
      id: 'shootr_1',
      role: UserRole.shootr,
      name: name,
      phone: phone,
      city: city,
      state: stateName,
      country: country,
      address: address,
      pinCode: pinCode,
      gender: gender,
      dateOfBirth: dateOfBirth,
      photoUrl: photoUrl,
      activeSince: DateTime.now(),
      accountStatus: AccountStatus.pendingReview,
      bio: bio,
      hourlyRate: hourlyRate,
      portfolio: portfolio.take(AppConstants.maxPortfolioItems).toList(),
      badges: const <String>['Pending Review'],
      deviceModel: deviceModel,
      deviceType: deviceType,
      deviceTier: deviceTier,
      deviceCameraSpec: deviceCameraSpec,
      availability: availability,
      todayAvailability: todayAvailability,
      onDemandMode: onDemandMode,
      payoutDetails: payoutDetails,
      upiId: upiId,
      bankName: bankName,
      ifscCode: ifscCode,
      completionRate: 100,
      referralCode: 'SHOOTR1000',
      specialisationIds: specialisationIds,
      latitude: latitude,
      longitude: longitude,
      operatingRadiusKm: operatingRadiusKm,
      hasDrone: hasDrone,
      identityStatus: identityStatus,
      deviceVerificationStatus: deviceVerificationStatus,
    );
  }
}
